class Bgp_rpc_data():

    def config_data(self):
        # DUT1 config rpc data
        self.dut1_d1 = '''<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id=""><edit-config><target><running/></target><config><bgp xmlns="http://ciena.com/ns/yang/ciena-bgp"><instance><as>65536</as><address-family  xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge"><afi>ipv4</afi><safi>unicast</safi></address-family></instance></bgp></config></edit-config></rpc>'''
        self.dut1_d2 = '''<edit-config><target><running/></target><config><bgp xmlns="http://ciena.com/ns/yang/ciena-bgp"><instance  xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge"><as>65536</as><router-id>1.1.1.1</router-id></instance></bgp></config></edit-config>'''
        self.dut1_d3 = '''<edit-config><target><running/></target><config><bgp xmlns="http://ciena.com/ns/yang/ciena-bgp"><instance><as>65536</as><address-family><afi>ipv4</afi><safi>unicast</safi><redistribute  xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge"><protocol>connected</protocol></redistribute></address-family></instance></bgp></config></edit-config>'''
        self.dut1_d4 = '''<edit-config><target><running/></target><config><bgp xmlns="http://ciena.com/ns/yang/ciena-bgp"><instance><as>65536</as><address-family  xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge"><afi>ipv4</afi><safi>unicast</safi></address-family></instance></bgp></config></edit-config>'''
        self.dut1_d5 = '''<edit-config><target><running/></target><config><bgp xmlns="http://ciena.com/ns/yang/ciena-bgp"><instance><as>65536</as><peer  xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge"><address>30.30.30.2</address><remote-as>65536</remote-as></peer></instance></bgp></config></edit-config>'''
        self.dut1_d6 = '''<edit-config><target><running/></target><config><bgp xmlns="http://ciena.com/ns/yang/ciena-bgp"><instance><as>65536</as><peer><address>30.30.30.2</address><address-family  xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge"><afi>ipv4</afi><safi>unicast</safi></address-family></peer></instance></bgp></config></edit-config>'''
        self.dut1_d7 = '''<edit-config><target><running/></target><config><bgp xmlns="http://ciena.com/ns/yang/ciena-bgp"><instance><as>65536</as><peer><address>30.30.30.2</address><address-family  xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge"><afi>ipv4</afi><safi>unicast</safi><activate>true</activate></address-family></peer></instance></bgp></config></edit-config>'''
        self.dut1_d8 = '''<edit-config><target><running/></target><config><bgp xmlns="http://ciena.com/ns/yang/ciena-bgp"><instance><as>65536</as><peer><address>30.30.30.2</address><address-family  xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge"><afi>ipv4</afi><safi>unicast</safi><next-hop-self>true</next-hop-self></address-family></peer></instance></bgp></config></edit-config>'''

        # DUT2 config rpc data
        self.dut2_d1 = '''<edit-config><target><running/></target><config><bgp xmlns="http://ciena.com/ns/yang/ciena-bgp"><instance><as>65536</as><address-family xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"nc:operation="merge"><afi>ipv4</afi><safi>unicast</safi></address-family></instance></bgp></config></edit-config>'''
        self.dut2_d2 = '''<edit-config><target><running/></target><config><bgp xmlns="http://ciena.com/ns/yang/ciena-bgp"><instance xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"nc:operation="merge"><as>65536</as><router-id>2.2.2.2</router-id></instance></bgp></config></edit-config>'''
        self.dut2_d3 = '''<edit-config><target><running/></target><config><bgp xmlns="http://ciena.com/ns/yang/ciena-bgp"><instance><as>65536</as><address-family><afi>ipv4</afi><safi>unicast</safi><redistribute  xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge"><protocol>connected</protocol></redistribute></address-family></instance></bgp></config></edit-config>'''
        self.dut2_d4 = '''<edit-config><target><running/></target><config><bgp xmlns="http://ciena.com/ns/yang/ciena-bgp"><instance><as>65536</as><address-family  xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge"><afi>ipv4</afi><safi>unicast</safi></address-family></instance></bgp></config></edit-config>'''
        self.dut2_d5 = '''<config><bgp xmlns="http://ciena.com/ns/yang/ciena-bgp"><instance><as>65536</as><peer  xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge"><address>30.30.30.1</address><remote-as>65536</remote-as></peer></instance></bgp></config></edit-config>'''
        self.dut2_d6 = '''<edit-config><target><running/></target><config><bgp xmlns="http://ciena.com/ns/yang/ciena-bgp"><instance><as>65536</as><peer><address>30.30.30.1</address><address-family  xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge"><afi>ipv4</afi><safi>unicast</safi></address-family></peer></instance></bgp></config></edit-config>'''
        self.dut2_d7 = '''<edit-config><target><running/></target><config><bgp xmlns="http://ciena.com/ns/yang/ciena-bgp"><instance><as>65536</as><peer><address>30.30.30.1</address><address-family  xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge"><afi>ipv4</afi><safi>unicast</safi><activate>true</activate></address-family></peer></instance></bgp></config></edit-config>'''
        self.dut2_d8 = '''<edit-config><target><running/></target><config><bgp xmlns="http://ciena.com/ns/yang/ciena-bgp"><instance><as>65536</as><peer><address>30.30.30.1</address><address-family xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"nc:operation="merge"><afi>ipv4</afi><safi>unicast</safi><next-hop-self>true</next-hop-self></address-family></peer></instance></bgp></config></edit-config>'''

        self.dut1_config_data = [self.dut1_d1, self.dut1_d2, self.dut1_d3, self.dut1_d4, self.dut1_d5, self.dut1_d6,
                                 self.dut1_d7, self.dut1_d8]
        self.dut2_config_data = [self.dut2_d1, self.dut2_d2, self.dut2_d3, self.dut2_d4, self.dut2_d5, self.dut2_d6,
                                 self.dut2_d7, self.dut2_d8]
