# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application Run
  
on:
  schedule:
     - cron: "0 0 * * *" #runs at 00:00 UTC everyday

SCRIPT_DIR =Network_Automation/BGP_AUTOMATION/Script

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: Set up Python 3.80
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt;
    - name: execute py script # run the bgp_auth_validation.py to get the latest data
      run: |
        export PYTHONPATH=BGP_AUTOMATION/Script
        export PYTHONPATH=BGP_AUTOMATION/Library
        python ${{ env.SCRIPT_DIR }}/bgp_auth_validation.py
        
